[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "fps-highlights"
version = "0.1.0"
dependencies = [
    "numpy",
    "moviepy",
    "fastai",
    "loguru",
    "tqdm",
]
